service: ecs-chaos-monkey

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  stage: alpha
  lambdaHashingVersion: 20201221
  region: "some_region"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ecs:ListServices
        - ecs:DeleteService
      Resource: "*"


functions:
  function:
    handler: handler.handler
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true
